# Generated by Django 3.0.7 on 2020-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_price', models.CharField(max_length=255)),
                ('zwl_price', models.CharField(max_length=255)),
                ('prop_title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'property',
            },
        ),
    ]
